import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The sidebar is generated from the directory tree. At M2 that tree stops
// being hand-written: channels/site/ syncs it from the reviewed corpus in
// targets/<name>/docs/, and the structure comes with it.
// See docs/decisions/0006-one-corpus-many-channels.md.

const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
